#!/usr/bin/env python3

import sys
import json
import os

OUTDIR = os.getenv('OUTDIR', '../htmlreader_output')
BOOK_URL = os.getenv('BOOK_URL',
                     'https://www.openbookpublishers.com/product/')
HTMLREADER_URL = os.getenv('HTMLREADER_URL',
                           'https://www.openbookpublishers.com/htmlreader/')


def run():
    _, metadata_path, epub_path = sys.argv
    with open(metadata_path) as f:
        metadata = json.load(f)

    epublius_dir = os.getcwd()

    exe = "./epublius_wrapper.py"
    args = [exe,
            "-p", os.path.join(epublius_dir, "prefix"),
            "-s", os.path.join(epublius_dir, "suffix"),
            "-h", os.path.join(epublius_dir, "header_add"),
            "-t", os.path.join(epublius_dir, ""),
            "-e", os.path.join(epublius_dir, ""),
            "-b", BOOK_URL + str(metadata['product_id']),
            "-f", epub_path,
            "-o", os.path.join(OUTDIR, metadata['isbn']),
            "-u", HTMLREADER_URL + metadata['isbn'],
            "-n", metadata['title'],
            "-r", "100"]

    os.execvp(sys.executable, [exe] + args)


if __name__ == '__main__':
    run()
